server:
  port: 8020
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices_hotelservice
    username: postgres
    password: Shubham0342@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true    
  application:
    name: HOTELSERVICE
   
  config:
    import: configserver:http://localhost:8085
    
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8760/eureka 